"""add join_time in users

Revision ID: 0446117a43be
Revises: d41a236f67b4
Create Date: 2019-03-22 12:00:30.772405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0446117a43be'
down_revision = 'd41a236f67b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_time')
    # ### end Alembic commands ###
